### ISSUE TITLE
CHANGELOG link on CurseForge links to the wrong page

### ISSUE THREAD

**Issue by StygianEmperor** [Crimix/jetboots#21]
Currently the `Jet-Boots-1.16.3-1.0.1.jar`'s **CHANGELOG** link in its description on CurseForge goes to 
[https://github.com/Crimix/jetboots/blob/1.15/CHANGELOG.md](https://github.com/Crimix/jetboots/blob/1.15/CHANGELOG.md)
and it should probably go to 
[https://github.com/Crimix/jetboots/blob/1.16/CHANGELOG.md](https://github.com/Crimix/jetboots/blob/1.16/CHANGELOG.md).
so I got confused until I looked this up again and dug a bit deeper this time.

Could partially explain the slower downloads on the new version - if people are like me they sometimes (perhaps foolishly) wait to update mods unless a release mentions it adds/fixes something they would notice. Hope that helps!

**Comment by Crimix** [comment]
Did not notice that, thank you.
I will get that changed ASAP :smile:

**Comment by Crimix** [comment]
It has been changed for both version `1.0.0` & `1.0.1` to point to the correct changelog
