### ISSUE TITLE
Game Crashes When Wearing Guardian Helmet, Chestplate, and Leggings When Right-Clicking Bed

### ISSUE THREAD

**Issue by ToxinZangoose** [Crimix/jetboots#23]
Hello,

I had this issue and wanted to report it since I hadn't seen it in the issues tab.

I had maxed out my jet boots to the highest level, and had only gotten started on leveling the helmet, chestplate, and leggings when I went to sleep at night.

To recreate, craft each of the pieces of armor, wear them, then right click to sleep.

My game version is 1.16.4 with several mods, I'm using the latest update of Jet Boots (1.1.0)

I am not using Optifine, but instead I'm using Performant.

If there's anything else needed, I will do what's needed.

Excellent mod, I can't wait to see how it advances!

**Comment by Crimix** [comment]
Hi thank you for the bug report.

Do you happen to have a crash report you can do a pastebin of?

**Comment by ToxinZangoose** [comment]
[crash-2021-04-01_18.27.49-client.txt](https://github.com/Crimix/jetboots/files/6339602/crash-2021-04-01_18.27.49-client.txt)

**Comment by Crimix** [comment]
Based on your crashlog it seems to be [ModularPowerArmor](https://github.com/lehjr/MachineMusePowersuits) that tries to cast my ItemHandler to one of their interfaces.
I will have a look at their code to see if I can make a PR to fix the issue
