### ISSUE TITLE
[1.20.1] Rocket Boots upgrade lets you get Jet Boots

### ISSUE THREAD

**Issue by vizthex123** [Crimix/jetboots#31]
![image](https://github.com/Crimix/jetboots/assets/31721920/eb351a93-4f30-4754-851a-8c7e06f18fa7)

I also noticed that every upgrade recipe has duplicates.
![image](https://github.com/Crimix/jetboots/assets/31721920/b76ea6a5-6e56-4707-a2b3-9d8e9a919cad)

 According to the recipe IDs, it seems like there's a separate set of them for JEI? I use REI, so it might be bugged.

Here's my log if ya need it:
[latest.log](https://github.com/Crimix/jetboots/files/15372532/latest.log)

**Comment by Crimix** [comment]
You should not be gitting duplicates of them.
It might have to do with some special handling I did for JEI

**Comment by vizthex123** [comment]
> You should not be getting duplicates of them. It might have to do with some special handling I did for JEI

could be it, yeah. Seems like i can't remove the recipes with JEI in their IDs either.

JEI should auto-detect the recipes (not fully sure how the mod works though, but that seems the most logical to me). I think it's worth testing to see what happens.

**Comment by Crimix** [comment]
The UI seems correct, there are some shared upgrades between the two boots, but they are not the same recipe
